### ISSUE TITLE
Updated Grammar files

### ISSUE THREAD

**Issue by johndpope** [yesme/protobuf-parser#1]
https://raw.githubusercontent.com/protostuff/protostuff-compiler/15d05631d3c9fc211fa898a9eecc46eb2578a92f/protostuff-parser/src/main/antlr4/io/protostuff/compiler/parser/ProtoParser.g4 

https://raw.githubusercontent.com/protostuff/protostuff-compiler/15d05631d3c9fc211fa898a9eecc46eb2578a92f/protostuff-parser/src/main/antlr4/io/protostuff/compiler/parser/ProtoLexer.g4

**Comment by yesme** [comment]
@johndpope Could you submit a pull request?

**Comment by paulvi** [comment]
Will this solve #2 proto3 support?

**Comment by johndpope** [comment]
@paulvi  - I think it will. 

I have a swift proto walker here 
https://github.com/johndpope/Antlr-Swift-runtime

closing out this ticket as a spring cleaning exercise.

**Comment by Restioson** [comment]
+1. What happened to this? Is Proto3 still planned? The PR was never made.

**Comment by johndpope** [comment]
if you download files above then drag and drop into webbrowse onyour fork on webpage - it's simple to create PR.

**Comment by Restioson** [comment]
Cool, I'll make it then. Wanted to make sure the repo was still active, looked a bit dead with last 8 month activity

**Comment by Restioson** [comment]
Made PR #4
